### ISSUE TITLE
home_page.dart widget error. 

### ISSUE THREAD

**Issue by The-Real-Thisas** [iamadeeb/Flutter-Meditation-App#2]
```log
 ~/Desktop/Flutter-Meditation-App/ [master*] flutter run
Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...
 └─Compiling, linking and signing...                         4.0s
Xcode build done.                                           11.8s

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building DiscoverPage(dirty, state: _DiscoverPageState#0d471):
No MediaQuery widget ancestor found.
LayoutBuilder widgets require a MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was:
  LayoutBuilder
The ownership chain for the affected widget is: "LayoutBuilder ← ScreenUtilInit ← MyApp ← [root]"
No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
This can happen because you have not added a WidgetsApp, CupertinoApp, or MaterialApp widget (those
widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above
those widgets.

The relevant error-causing widget was:
  DiscoverPage
  DiscoverPage:file:///Users/thisas/Desktop/Flutter-Meditation-App/lib/home_page.dart:18:5

When the exception was thrown, this was the stack:
#0      debugCheckHasMediaQuery.<anonymous closure> (package:flutter/src/widgets/debug.dart:221:7)
#1      debugCheckHasMediaQuery (package:flutter/src/widgets/debug.dart:236:4)
#2      MediaQuery.of (package:flutter/src/widgets/media_query.dart:837:12)
#3      ScreenUtil.screenWidth (package:flutter_screenutil/screen_util.dart:69:51)
#4      ScreenUtil.scaleWidth (package:flutter_screenutil/screen_util.dart:88:28)
#5      ScreenUtil.setWidth (package:flutter_screenutil/screen_util.dart:101:41)
#6      SizeExtension.w (package:flutter_screenutil/size_extension.dart:5:32)
#7      _DiscoverPageState.build (package:meditation/discover_page.dart:32:26)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705:27)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4754:11)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (22 frames)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#37     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#38     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (116 frames)
#154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#155    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#156    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (173 frames)
#329    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#330    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#331    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (396 frames)
#727    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#728    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#729    _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:137:18)
#730    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#731    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:154:12)
#732    RenderObject.invokeLayoutCallback.<anonymous closure>
(package:flutter/src/rendering/object.dart:1962:59)
#733    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:910:15)
#734    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1962:14)
#735    RenderConstrainedLayoutBuilder.rebuildIfNecessary
(package:flutter/src/widgets/layout_builder.dart:228:7)
#736    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:317:5)
#737    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#738    RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#739    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#740    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#741    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#742    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#743    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#744    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#745    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#746    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:863:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device iPhone 13...                               132ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 13 is available at: http://127.0.0.1:52043/m7flVuJxwT0=/
The Flutter DevTools debugger and profiler on iPhone 13 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:52043/m7flVuJxwT0=/
```
<img width="472" alt="Screen Shot 2022-01-28 at 2 57 33 PM" src="https://user-images.githubusercontent.com/59698123/151535294-3b767c5a-d9cf-4ef8-8242-8d9b42a4fc66.png">

**Comment by iamadeeb** [comment]
I just pushed a fix
